# ---------------------------------------------------------------------------
# xxxx.py
# Created on: 2012-04-19 08:36:11.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: xxxx <Coordinate_System> <Output_Personal_GDB> <Output_Location> <RCL_NAME> <ADD_NAME> <LM_NAME> <DWY_NAME> <Personal_GDB_Version> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy modules and toolboxes
import arcpy

def msg_show(msg):
	arcpy.AddMessage(msg)

# Script arguments
PGDBVersion = arcpy.GetParameterAsText(0)				# New Geodatabase Version
PGDBOutLoc = arcpy.GetParameterAsText(1)				# New Geodatabase Location
PGDBName = arcpy.GetParameterAsText(2)					# New Geodatabase Name
CoordSys = arcpy.GetParameterAsText(3)					# Feature Layer Coordinate System
ADD_NAME = arcpy.GetParameterAsText(4)					# Address Layer Name
LM_NAME = arcpy.GetParameterAsText(5)					# Landmark Layer Name
DWY_NAME = arcpy.GetParameterAsText(6)					# Driveway Layer Name
RCL_NAME = arcpy.GetParameterAsText(7)					# Road Centerline Layer Name

# Local Variables
FCOutLoc = PGDBOutLoc + "\\" + PGDBName + ".mdb"

msg_show("\n\nCreating Personal Geodatabase and Feature Classes...")

# Process: Create PGDB
arcpy.CreatePersonalGDB_management(PGDBOutLoc, PGDBName, PGDBVersion)
	
# Process: Create FeatureClasses
arcpy.CreateFeatureclass_management(FCOutLoc, ADD_NAME, "POINT", "", "DISABLED", "DISABLED", CoordSys, "", "0", "0", "0")
arcpy.CreateFeatureclass_management(FCOutLoc, LM_NAME, "POINT", "", "DISABLED", "DISABLED", CoordSys, "", "0", "0", "0")
arcpy.CreateFeatureclass_management(FCOutLoc, RCL_NAME, "POLYLINE", "", "DISABLED", "DISABLED", CoordSys, "", "0", "0", "0")
arcpy.CreateFeatureclass_management(FCOutLoc, DWY_NAME, "POLYLINE", "", "DISABLED", "DISABLED", CoordSys, "", "0", "0", "0")



# Process: Add Address Fields
msg_show("Adding Address Layer Fields...")
IL = FCOutLoc + "\\" + ADD_NAME
arcpy.AddField_management(IL, "FLAG", "TEXT", "", "", "2", "FLAG", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "ASIA_USER", "TEXT", "", "", "10", "ASIA_USER", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "DATE_NEW", "DATE", "", "", "", "DATE_NEW", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "DATE_MOD", "DATE", "", "", "", "DATE_MOD", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "POINTID", "TEXT", "", "", "15", "POINTID", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "NEW_ADD", "LONG", "8", "", "", "NEW_ADD", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "ALPHA", "TEXT", "", "", "15", "ALPHA", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "PREFIX", "TEXT", "", "", "2", "PREFIX", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "ROAD_NAME", "TEXT", "", "", "40", "ROAD_NAME", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "SUFFIX", "TEXT", "", "", "4", "SUFFIX", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "POSTDIR", "TEXT", "", "", "2", "POSTDIR", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "RDNAME", "TEXT", "", "", "51", "RDNAME", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "ALIAS", "TEXT", "", "", "51", "ALIAS", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "LAST_NAME", "TEXT", "", "", "50", "LAST_NAME", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "FIRST_NAME", "TEXT", "", "", "50", "FIRST_NAME", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "PHONE", "TEXT", "", "", "14", "PHONE", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "PHONE2", "TEXT", "", "", "14", "PHONE2", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "CITY", "TEXT", "", "", "32", "CITY", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "STATE", "TEXT", "", "", "2", "STATE", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "ZIP", "TEXT", "", "", "12", "ZIP", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "MAIL_ADD1", "TEXT", "", "", "6", "MAIL_ADD1", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "MAIL_ADD2", "TEXT", "", "", "50", "MAIL_ADD2", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "MAIL_CITY", "TEXT", "", "", "32", "MAIL_CITY", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "MAIL_STATE", "TEXT", "", "", "2", "MAIL_STATE", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "MAIL_ZIP", "TEXT", "", "", "12", "MAIL_ZIP", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "PLACE", "TEXT", "", "", "20", "PLACE", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "STRUCTURE", "TEXT", "", "", "20", "STRUCTURE", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "NOTE1", "TEXT", "", "", "150", "NOTE1", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "NOTE2", "TEXT", "", "", "150", "NOTE2", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "LB", "TEXT", "", "", "2", "LB", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "HOTLINK", "TEXT", "", "", "100", "HOTLINK", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "PARITY", "SHORT", "1", "", "", "PARITY", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "LASTCHANGE", "TEXT", "", "", "50", "LASTCHANGE", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "X", "DOUBLE", "", "", "", "X", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "Y", "DOUBLE", "", "", "", "Y", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "LONG", "DOUBLE", "", "", "", "LONG", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "LAT", "DOUBLE", "", "", "", "LAT", "NULLABLE", "NON_REQUIRED", "")



# Process: Add Road Centerline Fields
msg_show("Adding Road Centerline Layer Fields...")
IL = FCOutLoc + "\\" + RCL_NAME
arcpy.AddField_management(IL, "FLAG", "TEXT", "", "", "2", "FLAG", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "ASIA_USER", "TEXT", "", "", "10", "ASIA_USER", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "DATE_NEW", "DATE", "", "", "", "DATE_NEW", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "DATE_MOD", "DATE", "", "", "", "DATE_MOD", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "PREFIX", "TEXT", "", "", "2", "PREFIX", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "NAME", "TEXT", "", "", "40", "NAME", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "SUFFIX", "TEXT", "", "", "4", "SUFFIX", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "POSTDIR", "TEXT", "", "", "2", "POSTDIR", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "RDNAME", "TEXT", "", "", "51", "RDNAME", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "ALIAS", "TEXT", "", "", "51", "ALIAS", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "DIR", "TEXT", "", "", "4", "DIR", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "LEFT_FROM", "LONG", "6", "", "", "LEFT_FROM", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "LEFT_TO", "LONG", "6", "", "", "LEFT_TO", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "RIGHT_FROM", "LONG", "6", "", "", "RIGHT_FROM", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "RIGHT_TO", "LONG", "6", "", "", "RIGHT_TO", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "LEFTRANGE", "TEXT", "", "", "20", "LEFTRANGE", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "RIGHTRANGE", "TEXT", "", "", "20", "RIGHTRANGE", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "ESN", "LONG", "5", "", "", "ESN", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "EESN", "LONG", "5", "", "", "EESN", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "OESN", "LONG", "5", "", "", "OESN", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "COMM", "TEXT", "", "", "32", "COMM", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "ECOMM", "TEXT", "", "", "32", "ECOMM", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "OCOMM", "TEXT", "", "", "32", "OCOMM", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "TELCO", "TEXT", "", "", "4", "TELCO", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "ETELCO", "TEXT", "", "", "4", "ETELCO", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "OTELCO", "TEXT", "", "", "4", "OTELCO", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "CLASSIFI", "TEXT", "", "", "32", "CLASSIFI", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "LASTCHANGE", "TEXT", "", "", "50", "LASTCHANGE", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "INDEX", "LONG", "", "", "", "INDEX", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "RECORDID", "LONG", "", "", "", "RECORDID", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "SEGMENT_ID", "LONG", "", "", "", "SEGMENT_ID", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "LANES", "SHORT", "", "", "", "LANES", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "SPEED", "SHORT", "", "", "", "SPEED", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "WIDTH", "SHORT", "", "", "", "WIDTH", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "SURFACE", "TEXT", "", "", "30", "SURFACE", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "SHOULDER", "TEXT", "", "", "5", "SHOULDER", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "ONEWAY", "TEXT", "", "", "2", "ONEWAY", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "STATE", "TEXT", "", "", "2", "STATE", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "CNTYID", "TEXT", "", "", "4", "CNTYID", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "MAPLABEL", "TEXT", "", "", "25", "MAPLABEL", "NULLABLE", "NON_REQUIRED", "")



# Process: Add Landmark Fields
msg_show("Adding Landmark Layer Fields...")
IL = FCOutLoc + "\\" + LM_NAME
arcpy.AddField_management(IL, "FLAG", "TEXT", "", "", "2", "FLAG", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "DATE_NEW", "DATE", "", "", "", "DATE_NEW", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "DATE_MOD", "DATE", "", "", "", "DATE_MOD", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "TYPE", "TEXT", "", "", "30", "TYPE", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "DESCRIPTION", "TEXT", "", "", "50", "DESCRIPTION", "NULLABLE", "REQUIRED", "")
arcpy.AddField_management(IL, "CONDITION", "TEXT", "", "", "30", "CONDITION", "NULLABLE", "REQUIRED", "")



# Process: Add Driveway Fields
msg_show("Adding Driveway Layer Fields...")
IL = FCOutLoc + "\\" + DWY_NAME
arcpy.AddField_management(IL, "FLAG", "TEXT", "", "", "2", "FLAG", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "DATE_NEW", "DATE", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "DATE_MOD", "DATE", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")
arcpy.AddField_management(IL, "POINTID", "TEXT", "", "", "15", "", "NULLABLE", "NON_REQUIRED", "")
msg_show("\n\nDone!\n\n")
